recipe: default.v1
assistant_id: medical-assistant-2024
language: en

pipeline:
  # Basic text processing
  - name: WhitespaceTokenizer

  # Language model for medical terms understanding
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-uncased"
    cache_dir: "./cache"

  # Feature extraction
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer

  # Vector features for medical terms
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 3

  # Character level features (good for medical terms)
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 2
    max_ngram: 4

  # Intent and entity classification
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true
    batch_size: 128
    use_text_for_featurization: true
    evaluate_every_number_of_epochs: 10
    learning_rate: 0.001

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 150
    constrain_similarities: true
    batch_size: 128
    evaluate_every_number_of_epochs: 10
    learning_rate: 0.001

  # Higher threshold for medical domain accuracy
  - name: FallbackClassifier
    threshold: 0.65
    ambiguity_threshold: 0.15

policies:
  - name: MemoizationPolicy
    max_history: 8

  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true

  # Removed UnexpecTEDIntentPolicy as it's better for larger datasets

  - name: TEDPolicy
    max_history: 8
    epochs: 150
    batch_size: 128
    learning_rate: 0.001
    constrain_similarities: true
    evaluate_every_number_of_epochs: 10

action_server:
  url: "http://localhost:5055/webhook"

endpoints:
  action_endpoint:
    url: "http://localhost:5055/webhook"